### PR TITLE
fix(plugin): update tool may reset request or response parameters

### LINKED ISSUE #285: agent插件参数，配置好后重新进入，展示异常
首次进入智能体，配置好插件参数后

Image

再次进入

Image

### PR DESCRIPTION
**Pull request by mrh997**
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Add documentation if the current PR requires user awareness at the usage level.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
Bugs introduced by (PR)[https://github.com/coze-dev/coze-studio/pull/181]. When editing a tool, it may result in empty request or response parameters.

zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixes #285

### CODE REVIEW

File: backend/domain/plugin/service/plugin_draft.go [hunk 1]
```diff
@@ -647,8 +652,14 @@ func (p *pluginServiceImpl) UpdateDraftTool(ctx context.Context, req *UpdateTool
...
 
+	// update request parameters
+	if req.Parameters != nil {
+		op.Parameters = req.Parameters
+	}
+
+	// update request body
 	if req.RequestBody == nil {
-		op.RequestBody = draftTool.Operation.RequestBody
+		op.Operation.RequestBody = draftTool.Operation.RequestBody
```
Comment (junwen-lee) [inline backend/domain/plugin/service/plugin_draft.go]: op.RequestBody

Comment (mrh997) [reply backend/domain/plugin/service/plugin_draft.go]: done

**Review by junwen-lee — APPROVED** [review]
