### PR TITLE
fix(plugin): authorization code redirect to static url

### LINKED ISSUE #187: 飞书云文档认证回调
飞书云文档认证回调存在问题，问ai说是没有写回调逻辑，或者这块应该如何配置？

问题复现流程：

Image

Image
点击认证后页面链接：
https://xxx/api/oauth/authorization_code?code=4CGmB3f7K60a4HBAEd61aaxKc403HJdb&state=lxxKJ6q7QO8yWXPTAK1yA0HNBpQNDs4eemsHf2y5OqxuvSUbLvDv-SOy1gOxzU6HZYNbhEKkJ451iSwOVIh3QbGoXBvla8zGbr1XVcwnK8ub5djvkbk2b0a-cj2_BMMz

页面显示：
{"BaseResp":null}

相关日志信息：

2025/07/28 13:56:53 /app/domain/knowledge/internal/dal/dao/knowledge.go:163[1.011ms] [rows:1] SELECT count(*) FROM `knowledge` WHERE `knowledge`.`app_id` = 0 AND `knowledge`.`space_id` = 7532126385716854784 AND `knowledge`.`format_type` = 2 AND `knowledge`.`deleted_at` IS NULL 2025/07/28 13:56:53.261709 log.go:76: [Info] [log-id: 084bdc58-1dbc-4ece-8fc9-34fc1a65174e] | http | xxx | 200 | 13.309719ms | 185.81.28.69 | POST | /api/knowledge/list | coze.ListDataset | 0 ｜ en-US 
2025/07/28 13:56:53.261738 log.go:77: [Debug] [log-id: 084bdc58-1dbc-4ece-8fc9-34fc1a65174e] query :  
req : {"filter":{"scope_type":2,"format_type":2},"page":1,"size":20,"space_id":"7532126385716854784","order_field":1,"project_id":""} 
resp: {"dataset_list":[],"total":0,"code":0,"msg":"","BaseResp":null}
2025/07/28 13:57:53 /app/domain/plugin/internal/dal/plugin_oauth_auth.go:128 record not found[1.080ms] [rows:0] SELECT `plugin_oauth_auth`.`id` FROM `plugin_oauth_auth` WHERE `plugin_oauth_auth`.`user_id` = '7532126385704271872' AND `plugin_oauth_auth`.`plugin_id` = 19 AND `plugin_oauth_auth`.`is_draft` = false ORDER BY `plugin_oauth_auth`.`id` LIMIT 12025/07/28 13:57:53.563355 log.go:76: [Info] [log-id: 28a1efe2-e5ea-4722-8ac8-69fa5fa8bc5e] | http | xxx | 200 | 637.933711ms | 185.81.28.69 | GET | /api/oauth/authorization_code | coze.OauthAuthorizationCode | 0 ｜ en-US 
2025/07/28 13:57:53.563386 log.go:77: [Debug] [log-id: 28a1efe2-e5ea-4722-8ac8-69fa5fa8bc5e] query : code=4CGmB3f7K60a4HBAEd61aaxKc403HJdb&state=lxxKJ6q7QO8yWXPTAK1yA0HNBpQNDs4eemsHf2y5OqxuvSUbLvDv-SOy1gOxzU6HZYNbhEKkJ451iSwOVIh3QbGoXBvla8zGbr1XVcwnK8ub5djvkbk2b0a-cj2_BMMz 
req :  
resp: {"BaseResp":null}

聊天窗口再次提问，显示Something error:Internal server error

日志：

2025/07/28 14:04:02.467388 callback_reply_chunk.go:131: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnEnd, info={"Name":"","Type":"Default","Component":"ChatTemplate"}, output={"Result":[{"role":"user","content":""}],"Templates":[{"role":"user","content":""}],"Extra":null}
2025/07/28 14:04:02.467487 callback_reply_chunk.go:131: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnEnd, info={"Name":"","Type":"","Component":"Lambda"}, output=""
2025/07/28 14:04:02.467680 callback_reply_chunk.go:113: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnStart, info={"Name":"","Type":"","Component":"Lambda"}, input=null
2025/07/28 14:04:02.467769 callback_reply_chunk.go:131: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnEnd, info={"Name":"","Type":"","Component":"Lambda"}, output=""
2025/07/28 14:04:02.468242 callback_reply_chunk.go:113: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnStart, info={"Name":"","Type":"Default","Component":"ChatTemplate"}, input={"Variables":{"_chat_history":[{"role":"user","content":"创建文档 标题内容随便"},{"role":"assistant","content":"","tool_calls":[{"id":"create_document","type":"","function":{"name":"create_document","arguments":"{\"title\":\"新文档\"}"}}],"response_meta":{"finish_reason":"STOP","usage":{"prompt_tokens":582,"completion_tokens":14,"total_tokens":684}},"reasoning_content":"**Generating A Simple Document**\n\nI've decided to create a very simple title for the document, since the content and the title itself are arbitrary, per the request. I'll just generate an empty content body to go with it. I will now prepare to use the `create_document` tool with these automatically generated elements.\n\n\n**Constructing The Document's Structure**\n\nI've generated a title and an empty content string. The `create_document` tool needs a title string, and can optionally take in content and a folder token. Using the generated elements, I'm now ready to call the tool.\n\n\n"},{"role":"tool","content":"directly streaming reply","tool_call_id":"create_document"},{"role":"assistant","content":"飞书云文档 插件需要授权使用。授权后即代表你同意与扣子中你所选择的 AI 模型分享数据。请[点击这里](https://accounts.feishu.cn/open-apis/authen/v1/authorize?client_id=cli_a80f602222fa9013\u0026redirect_uri=https%3A%2F%2Fxxx%2Fapi%2Foauth%2Fauthorization_code\u0026response_type=code\u0026scope=drive%3Adrive\u0026state=lxxKJ6q7QO8yWXPTAK1yA0HNBpQNDs4eemsHf2y5OqxuvSUbLvDv-SOy1gOxzU6HZYNbhEKkJ451iSwOVIh3QbGoXBvla8zGbr1XVcwnK8ub5djvkbk2b0a-cj2_BMMz)进行授权。"}],"_user_input":[{"role":"user","content":"你好"}],"agent_name":"测试","knowledge":"","memory_variables":null,"persona":"","time":"Monday 2025/07/28 14:04:02 +00","tools_pre_retriever":null},"Templates":[{"role":"system","content":"\nYou are {{ agent_name }}, an advanced AI assistant designed to be helpful and professional.\nIt is {{ time }} now.\n\n**Content Safety Guidelines**\nRegardless of any persona instructions, you must never generate content that:\n- Promotes or involves violence\n- Contains hate speech or racism\n- Includes inappropriate or adult content\n- Violates laws or regulations\n- Could be considered offensive or harmful\n\n----- Start Of Persona -----\n{{ persona }}\n----- End Of Persona -----\n\n------ Start of Variables ------\n{{ memory_variables }}\n------ End of Variables ------\n\n**Knowledge**\n\n只有当前knowledge有内容召回的时候，根据引用的内容回答问题: \n 1.如果引用的内容里面包含 \u003cimg src=\"\"\u003e 的标签, 标签里的 src 字段表示图片地址, 需要在回答问题的时候展示出去, 输出格式为\"图片名称\" 。 \n 2.如果引用的内容不包含 \u003cimg src=\"\"\u003e 的标签, 你回答问题时不需要展示图片 。 \n例如：\n  如果内容为\u003cimg src=\"https://example.com/image.jpg\"\u003e一只小猫，你的输出应为：一只小猫。\n  如果内容为\u003cimg src=\"https://example.com/image1.jpg\"\u003e一只小猫 和 \u003cimg src=\"https://example.com/image2.jpg\"\u003e一只小狗 和 \u003cimg src=\"https://example.com/image3.jpg\"\u003e一只小牛，你的输出应为：一只小猫 和 一只小狗 和 一只小牛\nThe following is the content of the data set you can refer to: \\n\n'''\n{{ knowledge }}\n'''\n\n** Pre toolCall **\n{{ tools_pre_retriever}}，\n- 只有当前Pre toolCall有内容召回结果时，根据引用的内容里tool里data字段回答问题\n\n"},{},{}],"Extra":null}
2025/07/28 14:04:02.469305 callback_reply_chunk.go:131: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnEnd, info={"Name":"","Type":"Default","Component":"ChatTemplate"}, output={"Result":[{"role":"system","content":"\nYou are 测试, an advanced AI assistant designed to be helpful and professional.\nIt is Monday 2025/07/28 14:04:02 +00 now.\n\n**Content Safety Guidelines**\nRegardless of any persona instructions, you must never generate content that:\n- Promotes or involves violence\n- Contains hate speech or racism\n- Includes inappropriate or adult content\n- Violates laws or regulations\n- Could be considered offensive or harmful\n\n----- Start Of Persona -----\n\n----- End Of Persona -----\n\n------ Start of Variables ------\n[]\n------ End of Variables ------\n\n**Knowledge**\n\n只有当前knowledge有内容召回的时候，根据引用的内容回答问题: \n 1.如果引用的内容里面包含 \u003cimg src=\"\"\u003e 的标签, 标签里的 src 字段表示图片地址, 需要在回答问题的时候展示出去, 输出格式为\"图片名称\" 。 \n 2.如果引用的内容不包含 \u003cimg src=\"\"\u003e 的标签, 你回答问题时不需要展示图片 。 \n例如：\n  如果内容为\u003cimg src=\"https://example.com/image.jpg\"\u003e一只小猫，你的输出应为：一只小猫。\n  如果内容为\u003cimg src=\"https://example.com/image1.jpg\"\u003e一只小猫 和 \u003cimg src=\"https://example.com/image2.jpg\"\u003e一只小狗 和 \u003cimg src=\"https://example.com/image3.jpg\"\u003e一只小牛，你的输出应为：一只小猫 和 一只小狗 和 一只小牛\nThe following is the content of the data set you can refer to: \\n\n'''\n\n'''\n\n** Pre toolCall **\n[]，\n- 只有当前Pre toolCall有内容召回结果时，根据引用的内容里tool里data字段回答问题\n\n"},{"role":"user","content":"创建文档 标题内容随便"},{"role":"assistant","content":"","tool_calls":[{"id":"create_document","type":"","function":{"name":"create_document","arguments":"{\"title\":\"新文档\"}"}}],"response_meta":{"finish_reason":"STOP","usage":{"prompt_tokens":582,"completion_tokens":14,"total_tokens":684}},"reasoning_content":"**Generating A Simple Document**\n\nI've decided to create a very simple title for the document, since the content and the title itself are arbitrary, per the request. I'll just generate an empty content body to go with it. I will now prepare to use the `create_document` tool with these automatically generated elements.\n\n\n**Constructing The Document's Structure**\n\nI've generated a title and an empty content string. The `create_document` tool needs a title string, and can optionally take in content and a folder token. Using the generated elements, I'm now ready to call the tool.\n\n\n"},{"role":"tool","content":"directly streaming reply","tool_call_id":"create_document"},{"role":"assistant","content":"飞书云文档 插件需要授权使用。授权后即代表你同意与扣子中你所选择的 AI 模型分享数据。请[点击这里](https://accounts.feishu.cn/open-apis/authen/v1/authorize?client_id=cli_a80f602222fa9013\u0026redirect_uri=https%3A%2F%2Fxxx%2Fapi%2Foauth%2Fauthorization_code\u0026response_type=code\u0026scope=drive%3Adrive\u0026state=lxxKJ6q7QO8yWXPTAK1yA0HNBpQNDs4eemsHf2y5OqxuvSUbLvDv-SOy1gOxzU6HZYNbhEKkJ451iSwOVIh3QbGoXBvla8zGbr1XVcwnK8ub5djvkbk2b0a-cj2_BMMz)进行授权。"},{"role":"user","content":"你好"}],"Templates":[{"role":"system","content":"\nYou are {{ agent_name }}, an advanced AI assistant designed to be helpful and professional.\nIt is {{ time }} now.\n\n**Content Safety Guidelines**\nRegardless of any persona instructions, you must never generate content that:\n- Promotes or involves violence\n- Contains hate speech or racism\n- Includes inappropriate or adult content\n- Violates laws or regulations\n- Could be considered offensive or harmful\n\n----- Start Of Persona -----\n{{ persona }}\n----- End Of Persona -----\n\n------ Start of Variables ------\n{{ memory_variables }}\n------ End of Variables ------\n\n**Knowledge**\n\n只有当前knowledge有内容召回的时候，根据引用的内容回答问题: \n 1.如果引用的内容里面包含 \u003cimg src=\"\"\u003e 的标签, 标签里的 src 字段表示图片地址, 需要在回答问题的时候展示出去, 输出格式为\"图片名称\" 。 \n 2.如果引用的内容不包含 \u003cimg src=\"\"\u003e 的标签, 你回答问题时不需要展示图片 。 \n例如：\n  如果内容为\u003cimg src=\"https://example.com/image.jpg\"\u003e一只小猫，你的输出应为：一只小猫。\n  如果内容为\u003cimg src=\"https://example.com/image1.jpg\"\u003e一只小猫 和 \u003cimg src=\"https://example.com/image2.jpg\"\u003e一只小狗 和 \u003cimg src=\"https://example.com/image3.jpg\"\u003e一只小牛，你的输出应为：一只小猫 和 一只小狗 和 一只小牛\nThe following is the content of the data set you can refer to: \\n\n'''\n{{ knowledge }}\n'''\n\n** Pre toolCall **\n{{ tools_pre_retriever}}，\n- 只有当前Pre toolCall有内容召回结果时，根据引用的内容里tool里data字段回答问题\n\n"},{},{}],"Extra":null}
2025/07/28 14:04:02.469651 callback_reply_chunk.go:113: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnStart, info={"Name":"re_act_chat_model","Type":"Gemini","Component":"ChatModel"}, input={"Messages":[{"role":"system","content":"\nYou are 测试, an advanced AI assistant designed to be helpful and professional.\nIt is Monday 2025/07/28 14:04:02 +00 now.\n\n**Content Safety Guidelines**\nRegardless of any persona instructions, you must never generate content that:\n- Promotes or involves violence\n- Contains hate speech or racism\n- Includes inappropriate or adult content\n- Violates laws or regulations\n- Could be considered offensive or harmful\n\n----- Start Of Persona -----\n\n----- End Of Persona -----\n\n------ Start of Variables ------\n[]\n------ End of Variables ------\n\n**Knowledge**\n\n只有当前knowledge有内容召回的时候，根据引用的内容回答问题: \n 1.如果引用的内容里面包含 \u003cimg src=\"\"\u003e 的标签, 标签里的 src 字段表示图片地址, 需要在回答问题的时候展示出去, 输出格式为\"图片名称\" 。 \n 2.如果引用的内容不包含 \u003cimg src=\"\"\u003e 的标签, 你回答问题时不需要展示图片 。 \n例如：\n  如果内容为\u003cimg src=\"https://example.com/image.jpg\"\u003e一只小猫，你的输出应为：一只小猫。\n  如果内容为\u003cimg src=\"https://example.com/image1.jpg\"\u003e一只小猫 和 \u003cimg src=\"https://example.com/image2.jpg\"\u003e一只小狗 和 \u003cimg src=\"https://example.com/image3.jpg\"\u003e一只小牛，你的输出应为：一只小猫 和 一只小狗 和 一只小牛\nThe following is the content of the data set you can refer to: \\n\n'''\n\n'''\n\n** Pre toolCall **\n[]，\n- 只有当前Pre toolCall有内容召回结果时，根据引用的内容里tool里data字段回答问题\n\n"},{"role":"user","content":"创建文档 标题内容随便"},{"role":"assistant","content":"","tool_calls":[{"id":"create_document","type":"","function":{"name":"create_document","arguments":"{\"title\":\"新文档\"}"}}],"response_meta":{"finish_reason":"STOP","usage":{"prompt_tokens":582,"completion_tokens":14,"total_tokens":684}},"reasoning_content":"**Generating A Simple Document**\n\nI've decided to create a very simple title for the document, since the content and the title itself are arbitrary, per the request. I'll just generate an empty content body to go with it. I will now prepare to use the `create_document` tool with these automatically generated elements.\n\n\n**Constructing The Document's Structure**\n\nI've generated a title and an empty content string. The `create_document` tool needs a title string, and can optionally take in content and a folder token. Using the generated elements, I'm now ready to call the tool.\n\n\n"},{"role":"tool","content":"directly streaming reply","tool_call_id":"create_document"},{"role":"assistant","content":"飞书云文档 插件需要授权使用。授权后即代表你同意与扣子中你所选择的 AI 模型分享数据。请[点击这里](https://accounts.feishu.cn/open-apis/authen/v1/authorize?client_id=cli_a80f602222fa9013\u0026redirect_uri=https%3A%2F%2Fxxx%2Fapi%2Foauth%2Fauthorization_code\u0026response_type=code\u0026scope=drive%3Adrive\u0026state=lxxKJ6q7QO8yWXPTAK1yA0HNBpQNDs4eemsHf2y5OqxuvSUbLvDv-SOy1gOxzU6HZYNbhEKkJ451iSwOVIh3QbGoXBvla8zGbr1XVcwnK8ub5djvkbk2b0a-cj2_BMMz)进行授权。"},{"role":"user","content":"你好"}],"Tools":[{"Name":"create_document","Desc":"创建文档，支持创建空文档和带内容的文档，支持 markdown 语法创建。"}],"ToolChoice":null,"Config":{"Model":"gemini-2.5-flash","MaxTokens":4096,"Temperature":0.7,"TopP":1,"Stop":null},"Extra":null}
2025/07/28 14:04:02.469813 callback_reply_chunk.go:67: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnError, info={"Name":"re_act_chat_model","Type":"Gemini","Component":"ChatModel"}, err=convert schema message fail: convert schema message fail: unmarshal schema tool call response to map[string]any fail: "Syntax error at index 1: invalid char\n\n\tdirectly streaming reply\n\t.^......................\n"
2025/07/28 14:04:02.469862 callback_reply_chunk.go:67: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnError, info={"Name":"react_agent","Type":"","Component":"Graph"}, err=[NodeRunError]convert schema message fail: convert schema message fail: unmarshal schema tool call response to map[string]any fail: "Syntax error at index 1: invalid char\n\n\tdirectly streaming reply\n\t.^......................\n"
------------------------
node path: [chat]2025/07/28 14:04:02.469965 callback_reply_chunk.go:97: [Error] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] node execute failed, component=Graph, name=react_agent, err=[NodeRunError]convert schema message fail: convert schema message fail: unmarshal schema tool call response to map[string]any fail: "Syntax error at index 1: invalid char\n\n\tdirectly streaming reply\n\t.^......................\n"
------------------------
node path: [chat]2025/07/28 14:04:02.470121 agent_run_impl.go:486: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] hanlder event:{"EventType":"","ModelAnswer":null,"ToolsMessage":null,"FuncCall":null,"Suggest":null,"Knowledge":null,"Interrupt":null,"Err":{}},err:Internal server error
2025/07/28 14:04:02.470370 callback_reply_chunk.go:67: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] info-OnError, info={"Name":"","Type":"","Component":"Graph"}, err=[NodeRunError]convert schema message fail: convert schema message fail: unmarshal schema tool call response to map[string]any fail: "Syntax error at index 1: invalid char\n\n\tdirectly streaming reply\n\t.^......................\n"
------------------------
node path: [react_agent, chat]2025/07/28 14:04:02.470385 callback_reply_chunk.go:97: [Error] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] node execute failed, component=Graph, name=, err=[NodeRunError]convert schema message fail: convert schema message fail: unmarshal schema tool call response to map[string]any fail: "Syntax error at index 1: invalid char\n\n\tdirectly streaming reply\n\t.^......................\n"
------------------------
node path: [react_agent, chat]2025/07/28 14:04:02.475163 log.go:76: [Info] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] | http | xxx | 200 | 48.761027ms | 185.81.28.69 | POST | /api/conversation/chat | coze.AgentRun | 0 ｜ en-US 
2025/07/28 14:04:02.475195 log.go:77: [Debug] [log-id: 53ee8519-3bb5-4ecf-9ad1-a50146f2fdb3] query :  
req : {"bot_id":"7532126527807291392","conversation_id":"7532126922688430080","local_message_id":"-nSafClc2KCF-FHjvB52H","content_type":"text","query":"你好","extra":{},"scene":4,"draft_mode":true,"stream":true,"chat_history":[],"mention_list":[],"space_id":"7532126385716854784"} 
resp: 

_刷新页面，清空对话记录，再次测试文档创建成功_

Image

env文件修改位置：
export SERVER_HOST="域名"

### PR DESCRIPTION
**Pull request by mrh997**
#### What type of PR is this?

fix

#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Add documentation if the current PR requires user awareness at the usage level.

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

Fixed the issue that the page was not closed automatically after OAuth authorization.

#### (Optional) Which issue(s) this PR fixes:

Fixes #187

### CODE REVIEW

File: backend/domain/plugin/service/plugin_oauth.go [hunk 1]
```diff
@@ -458,7 +458,7 @@ func getStanderOAuthConfig(config *model.OAuthAuthorizationCodeConfig) *oauth2.C
 			TokenURL: config.AuthorizationURL,
 			AuthURL:  config.ClientURL,
 		},
-		RedirectURL: fmt.Sprintf("https://%s/api/oauth/authorization_code", os.Getenv("SERVER_HOST")),
```
Comment (fanlv) [inline backend/domain/plugin/service/plugin_oauth.go:467]: 是不是用的 `https` 是不是不能随便假设？ 用户有可能前面加个了 `nginx` 自己做了 `https`。https://github.com/coze-dev/coze-studio/issues/131#issuecomment-3130701817  类似这种。

Comment (mrh997) [reply backend/domain/plugin/service/plugin_oauth.go:467]: 这是要改的，我还没改好。之前和你应该对过，类似 useSSL := strings.HasPrefix(apiHost, "https://") 这种处理方式。由于之前那版没有要求用户在 SERVER_HOST 中填 schema ，所以得加兜底逻辑默认为 https 。

Comment (mrh997) [reply backend/domain/plugin/service/plugin_oauth.go:467]: 再看看
